**1.	Write a Python Program to Add Two Matrices?**

In [1]:
import numpy as np

a = np.matrix([[1,2,7,8],[3,4,9,10],[15,18,20,22]])
b = np.matrix([[3,4,11,12],[5,6,13,14],[14,34,44,54]])

print(a+b)

[[ 4  6 18 20]
 [ 8 10 22 24]
 [29 52 64 76]]


**2.	Write a Python Program to Multiply Two Matrices?**

In [2]:
import numpy as np

a = np.matrix([[1,2,7,8],[3,4,9,10],[15,18,20,22]])
b = np.matrix([[3,4,11,12],[5,6,13,14],[14,34,44,54],[16,28,76,42]])

print(a*b)

[[ 239  478  953  754]
 [ 315  622 1241  998]
 [ 767 1464 2951 2436]]


**3.	Write a Python Program to Transpose a Matrix?**

In [3]:
import numpy as np

a = np.matrix([[1,2,7,8],[3,4,9,10],[15,18,20,22]])
print(a.T)

[[ 1  3 15]
 [ 2  4 18]
 [ 7  9 20]
 [ 8 10 22]]


**4.	Write a Python Program to Sort Words in Alphabetic Order?**

In [4]:
w = input('Enter a word- ')
print(sorted(w))

Enter a word- python
['h', 'n', 'o', 'p', 't', 'y']


**5.	Write a Python Program to Remove Punctuation From a String?**

In [5]:
p = ''' ! () - [] {} : ; ' " \ , <> . / ? @ # $ % ^ & * _ ~ '''
s = input('Enter a string- ')
for i in s:
    if i in p:
        s = s.replace(i , ' ')

print(s)

Enter a string- hello!!what are your plans@ for# today?*/
hello  what are your plans  for  today   
